spring:
  servlet:
    multipart:
      max-file-size: 1TB
      max-request-size: 1TB
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI4GHZsTFReYWLaZzwu4EY
    access-key-secret: eL92/8B1Oss97Vmf7tt3aQE+4f5/8wlOyJK1DF25Qjo=
    bucket-name: testdddddd1